[package]
name = "x_framesim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "framesim"
path = "src/main.rs"

[dependencies]
alvr_client_core.workspace = true
alvr_common.workspace = true
alvr_packets.workspace = true
alvr_session.workspace = true
alvr_sockets.workspace = true
alvr_system_info.workspace = true
env_logger = "0.11"
flate2 = "1"
libloading = "0.8"
log = "0.4"
